# -*- coding: utf-8 -*-
from billgate.models import db, BaseMixin
from billgate.models import User
from uuid import uuid4
from datetime import datetime

__all__ = ['Address']

countries = [
    ('AFG', u'Afghanistan'),
    ('ALA', u'Åland Islands'),
    ('ALB', u'Albania'),
    ('DZA', u'Algeria'),
    ('ASM', u'American Samoa'),
    ('AND', u'Andorra'),
    ('AGO', u'Angola'),
    ('AIA', u'Anguilla'),
    ('ATA', u'Antarctica'),
    ('ATG', u'Antigua and Barbuda'),
    ('ARG', u'Argentina'),
    ('ARM', u'Armenia'),
    ('ABW', u'Aruba'),
    ('AUS', u'Australia'),
    ('AUT', u'Austria'),
    ('AZE', u'Azerbaijan'),
    ('BHS', u'Bahamas'),
    ('BHR', u'Bahrain'),
    ('BGD', u'Bangladesh'),
    ('BRB', u'Barbados'),
    ('BLR', u'Belarus'),
    ('BEL', u'Belgium'),
    ('BLZ', u'Belize'),
    ('BEN', u'Benin'),
    ('BMU', u'Bermuda'),
    ('BTN', u'Bhutan'),
    ('BOL', u'Bolivia'),
    ('BIH', u'Bosnia and Herzegovina'),
    ('BWA', u'Botswana'),
    ('BVT', u'Bouvet Island'),
    ('BRA', u'Brazil'),
    ('IOT', u'British Indian Ocean Territory'),
    ('BRN', u'Brunei Darussalam'),
    ('BGR', u'Bulgaria'),
    ('BFA', u'Burkina Faso'),
    ('BDI', u'Burundi'),
    ('KHM', u'Cambodia'),
    ('CMR', u'Cameroon'),
    ('CAN', u'Canada'),
    ('CPV', u'Cape Verde'),
    ('CYM', u'Cayman Islands'),
    ('CAF', u'Central African Republic'),
    ('TCD', u'Chad'),
    ('CHL', u'Chile'),
    ('CHN', u'China'),
    ('CXR', u'Christmas Island'),
    ('CCK', u'Cocos (Keeling) Islands'),
    ('COL', u'Colombia'),
    ('COM', u'Comoros'),
    ('COG', u'Congo'),
    ('COD', u'Congo, the Democratic Republic of the'),
    ('COK', u'Cook Islands'),
    ('CRI', u'Costa Rica'),
    ('HRV', u'Croatia'),
    ('CUB', u'Cuba'),
    ('CYP', u'Cyprus'),
    ('CZE', u'Czech Republic'),
    ('CIV', u"Côte d'Ivoire"),
    ('DNK', u'Denmark'),
    ('DJI', u'Djibouti'),
    ('DMA', u'Dominica'),
    ('DOM', u'Dominican Republic'),
    ('ECU', u'Ecuador'),
    ('EGY', u'Egypt'),
    ('SLV', u'El Salvador'),
    ('GNQ', u'Equatorial Guinea'),
    ('ERI', u'Eritrea'),
    ('EST', u'Estonia'),
    ('ETH', u'Ethiopia'),
    ('FLK', u'Falkland Islands (Malvinas)'),
    ('FRO', u'Faroe Islands'),
    ('FJI', u'Fiji'),
    ('FIN', u'Finland'),
    ('FRA', u'France'),
    ('GUF', u'French Guiana'),
    ('PYF', u'French Polynesia'),
    ('ATF', u'French Southern Territories'),
    ('GAB', u'Gabon'),
    ('GMB', u'Gambia'),
    ('GEO', u'Georgia'),
    ('DEU', u'Germany'),
    ('GHA', u'Ghana'),
    ('GIB', u'Gibraltar'),
    ('GRC', u'Greece'),
    ('GRL', u'Greenland'),
    ('GRD', u'Grenada'),
    ('GLP', u'Guadeloupe'),
    ('GUM', u'Guam'),
    ('GTM', u'Guatemala'),
    ('GGY', u'Guernsey'),
    ('GNB', u'Guinea-Bissau'),
    ('GUY', u'Guyana'),
    ('HTI', u'Haiti'),
    ('HMD', u'Heard Island and McDonald Islands'),
    ('VAT', u'Holy See (Vatican City State)'),
    ('HND', u'Honduras'),
    ('HKG', u'Hong Kong'),
    ('HUN', u'Hungary'),
    ('ISL', u'Iceland'),
    ('IND', u'India'),
    ('IDN', u'Indonesia'),
    ('IRN', u'Iran, Islamic Republic of'),
    ('IRQ', u'Iraq'),
    ('IRL', u'Ireland'),
    ('IMN', u'Isle of Man'),
    ('ISR', u'Israel'),
    ('ITA', u'Italy'),
    ('JAM', u'Jamaica'),
    ('JPN', u'Japan'),
    ('JEY', u'Jersey'),
    ('JOR', u'Jordan'),
    ('KAZ', u'Kazakhstan'),
    ('KEN', u'Kenya'),
    ('KIR', u'Kiribati'),
    ('PRK', u"Korea, Democratic People's Republic of"),
    ('KOR', u'Korea, Republic of'),
    ('KWT', u'Kuwait'),
    ('KGZ', u'Kyrgyzstan'),
    ('LAO', u"Lao People's Democratic Republic"),
    ('LVA', u'Latvia'),
    ('LBN', u'Lebanon'),
    ('LSO', u'Lesotho'),
    ('LBR', u'Liberia'),
    ('LBY', u'Libyan Arab Jamahiriya'),
    ('LIE', u'Liechtenstein'),
    ('LTU', u'Lithuania'),
    ('LUX', u'Luxembourg'),
    ('MAC', u'Macao'),
    ('MKD', u'Macedonia, the former Yugoslav Republic of'),
    ('MDG', u'Madagascar'),
    ('MWI', u'Malawi'),
    ('MYS', u'Malaysia'),
    ('MDV', u'Maldives'),
    ('MLI', u'Mali'),
    ('MLT', u'Malta'),
    ('MHL', u'Marshall Islands'),
    ('MTQ', u'Martinique'),
    ('MRT', u'Mauritania'),
    ('MUS', u'Mauritius'),
    ('MYT', u'Mayotte'),
    ('MEX', u'Mexico'),
    ('FSM', u'Micronesia, Federated States of'),
    ('MDA', u'Moldova'),
    ('MCO', u'Monaco'),
    ('MNG', u'Mongolia'),
    ('MNE', u'Montenegro'),
    ('MSR', u'Montserrat'),
    ('MAR', u'Morocco'),
    ('MOZ', u'Mozambique'),
    ('MMR', u'Myanmar'),
    ('GIN', u'N Guinea'),
    ('NAM', u'Namibia'),
    ('NRU', u'Nauru'),
    ('NPL', u'Nepal'),
    ('NLD', u'Netherlands'),
    ('ANT', u'Netherlands Antilles'),
    ('NCL', u'New Caledonia'),
    ('NZL', u'New Zealand'),
    ('NIC', u'Nicaragua'),
    ('NER', u'Niger'),
    ('NGA', u'Nigeria'),
    ('NIU', u'Niue'),
    ('NFK', u'Norfolk Island'),
    ('MNP', u'Northern Mariana Islands'),
    ('OMN', u'Oman'),
    ('PAK', u'Pakistan'),
    ('PLW', u'Palau'),
    ('PSE', u'Palestinian Territory, Occupied'),
    ('PAN', u'Panama'),
    ('PNG', u'Papua New Guinea'),
    ('PRY', u'Paraguay'),
    ('PER', u'Peru'),
    ('PHL', u'Philippines'),
    ('PCN', u'Pitcairn'),
    ('POL', u'Poland'),
    ('PRT', u'Portugal'),
    ('PRI', u'Puerto Rico'),
    ('QAT', u'Qatar'),
    ('NOR', u'R Norway'),
    ('ROU', u'Romania'),
    ('RUS', u'Russian Federation'),
    ('RWA', u'Rwanda'),
    ('REU', u'Réunion'),
    ('BLM', u'Saint Barthélemy'),
    ('SHN', u'Saint Helena'),
    ('KNA', u'Saint Kitts and Nevis'),
    ('LCA', u'Saint Lucia'),
    ('MAF', u'Saint Martin (French part)'),
    ('SPM', u'Saint Pierre and Miquelon'),
    ('VCT', u'Saint Vincent and the Grenadines'),
    ('WSM', u'Samoa'),
    ('SMR', u'San Marino'),
    ('STP', u'Sao Tome and Principe'),
    ('SAU', u'Saudi Arabia'),
    ('SEN', u'Senegal'),
    ('SRB', u'Serbia'),
    ('SYC', u'Seychelles'),
    ('SLE', u'Sierra Leone'),
    ('SGP', u'Singapore'),
    ('SVK', u'Slovakia'),
    ('SVN', u'Slovenia'),
    ('SLB', u'Solomon Islands'),
    ('SOM', u'Somalia'),
    ('ZAF', u'South Africa'),
    ('SGS', u'South Georgia and the South Sandwich Islands'),
    ('ESP', u'Spain'),
    ('LKA', u'Sri Lanka'),
    ('SDN', u'Sudan'),
    ('SUR', u'Suriname'),
    ('SJM', u'Svalbard and Jan Mayen'),
    ('SWZ', u'Swaziland'),
    ('SWE', u'Sweden'),
    ('CHE', u'Switzerland'),
    ('SYR', u'Syrian Arab Republic'),
    ('TWN', u'Taiwan, Province of China'),
    ('TJK', u'Tajikistan'),
    ('TZA', u'Tanzania, United Republic of'),
    ('THA', u'Thailand'),
    ('TLS', u'Timor-Leste'),
    ('TGO', u'Togo'),
    ('TKL', u'Tokelau'),
    ('TON', u'Tonga'),
    ('TTO', u'Trinidad and Tobago'),
    ('TUN', u'Tunisia'),
    ('TUR', u'Turkey'),
    ('TKM', u'Turkmenistan'),
    ('TCA', u'Turks and Caicos Islands'),
    ('TUV', u'Tuvalu'),
    ('UGA', u'Uganda'),
    ('UKR', u'Ukraine'),
    ('ARE', u'United Arab Emirates'),
    ('GBR', u'United Kingdom'),
    ('USA', u'United States'),
    ('UMI', u'United States Minor Outlying Islands'),
    ('URY', u'Uruguay'),
    ('UZB', u'Uzbekistan'),
    ('VUT', u'Vanuatu'),
    ('VEN', u'Venezuela'),
    ('VNM', u'Viet Nam'),
    ('VGB', u'Virgin Islands, British'),
    ('VIR', u'Virgin Islands, U.S.'),
    ('WLF', u'Wallis and Futuna'),
    ('ESH', u'Western Sahara'),
    ('YEM', u'Yemen'),
    ('ZMB', u'Zambia'),
    ('ZWE', u'Zimbabwe'),
    ]

class Address(BaseMixin, db.Model):
    __tablename__ = 'address'
    
    # address must be unique within a user scope
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relation(User, backref=db.backref('addresses', cascade='all, delete-orphan'))

    #for session persistence
    hashkey = db.Column(db.Unicode(250), default=uuid4().hex, nullable=True)

    name = db.Column(db.Unicode(250), default=u'', nullable=True)
    address = db.Column(db.Unicode(1200), default=u'', nullable=True)
    city = db.Column(db.Unicode(250), default=u'', nullable=True)
    state = db.Column(db.Unicode(250), default=u'', nullable=True)
    postal_code = db.Column(db.Unicode(6), default=u'', nullable=True)
    country = db.Column(db.Unicode(250), default=u'', nullable=True) 
    phone = db.Column(db.Unicode(15), default=u'', nullable=True)
    email = db.Column(db.Unicode(80), default=u'', nullable=True)

    @classmethod
    def get(cls, user):
        return cls.query.filter_by(user=user)

    @classmethod
    def get_by_hashkey(cls, hashkey):
        return Address.query.filter_by(hashkey=hashkey)